#!/bin/sh
CC=g++
CFLAGS="-O3 -march=native -std=c++11 -fopenmp"

echo $CC $CFLAGS '-o generate_v.exe src/generate_v.cpp'
$CC $CFLAGS -o generate_v.exe src/generate_v.cpp

echo $CC $CFLAGS '-o mining_v.exe src/mining_v.cpp'
$CC $CFLAGS -o mining_v.exe src/mining_v.cpp

echo $CC $CFLAGS '-o scoring_v.exe src/scoring_v.cpp'
$CC $CFLAGS -o scoring_v.exe src/scoring_v.cpp

